name: CD

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: jenkins-infra/jenkins-maven-cd-action/.github/workflows/cd.yaml@v2
    with:
      git-email: "66257131+QAwangyang@users.noreply.github.com"
      git-name: "QAwangyang"
